language: go

go:
  - 1.12.x

env:
  - GO111MODULE=on GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org

script:
  - ./ci/check_go_fmt.sh
  - ./ci/check_go_generate.sh
  - go test --race -v ./...
